services:
  jupyter:
    build: ./
    ports:
      - "10000:8888"
      - "4040:4040"
    volumes:
      - ./synthetic_data:/home/jovyan/source
      - ../data_lake:/home/jovyan/data_lake
      - ./jupyter_notebook:/home/jovyan
    command: sudo jupyter notebook --no-browser --NotebookApp.token='' --NotebookApp.password='' --ip='*' --allow-root
    environment:
      - GRANT_SUDO=yes
      - CHOWN_EXTRA_OPTS='-R'
    user: root
    restart: always
    networks:
    - market
networks:
  market: 