services:

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: de_clickhouse
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse:/var/lib/clickhouse
      - ../data_lake:/opt/data_lake
      - ./docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
    networks:
      - market
volumes:
  clickhouse:

networks:
  market: 
    external: true
    name: de_frontend     