services:
  certbot:
    image: certbot/certbot:latest
    container_name: de_certbot
    volumes:
      - ./www:/var/www/html:ro
      - ./conf:/etc/letsencrypt:rw
      - ../nginx/certs:/etc/nginx/certs:rw
    environment:
      - DOMAIN_EMAIL=jeaf@ya.ru
      - DOMAIN_URL=de-project.space
    entrypoint: |
      sh -c 'certbot certonly --webroot --webroot-path /var/www/html \
      --email $${DOMAIN_EMAIL} -d $${DOMAIN_URL},www.$${DOMAIN_URL},airflow.$${DOMAIN_URL}, inio.$${DOMAIN_URL},spark.$${DOMAIN_URL},ngnix-ui.$${DOMAIN_URL},jupyter.$${DOMAIN_URL}\
      --agree-tos --non-interactive --keep-until-expiring \
      --cert-name $${DOMAIN_URL}'
    networks:
      - frontend
    restart: no

networks:
  frontend:
    external: true
    name: de_frontend
