services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./www/:/var/www/certbot/:rw
      - ./conf/:/etc/letsencrypt/:rw

networks:
  frontend:
    external: true
    name: de_frontend