
services:
  nginx:
    image: nginx:latest
    container_name: de_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./logs:/var/log/nginx
      - ./sites-available:/etc/nginx/sites-available 
      - ./sites-enabled:/etc/nginx/sites-enabled 
      - ./html:/var/www/html/
      
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
    name: de_frontend