
services:
  nginx:
    image: nginx:latest
    container_name: de_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      
      - ./conf.d:/etc/nginx/conf.d
      - ../certbot/www:/var/www/certbot
      - ../certbot/conf/live/de-project.space:/etc/nginx/certs
      - ./html:/var/www/html
      
      
      
      
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
    name: de_frontend