
services:
  nginx:
    image: nginx:latest
    container_name: de_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/etc/nginx/
      - ./html:/var/www/html
      - ../certbot/www/:/var/www/html
      - ../certbot/conf/live/de-project.space:/etc/ngnix/certs
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
    name: de_frontend