
services:
  nginx:
    image: nginx:latest
    container_name: de_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/etc/nginx/
      - ./certs:/etc/nginx/certs
      - ./html:/var/www/html
      - ../certbot/www/:/var/www/html
      
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
    name: de_frontend