
services:
  nginx:
    image: nginx:latest
    container_name: de_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/etc/nginx/
      - ./certs/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/nginx/certs/privkey.pem
      - ./html:/var/www/html
      
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
    name: de_frontend