services:
    nginx-ui:
        stdin_open: true
        tty: true
        container_name: nginx-ui
        restart: always
        
        volumes:
            - ./nginx:/etc/nginx
            - ./nginx-ui:/etc/nginx-ui
            - ./www:/var/www
        ports:
            - 8080:80
            - 8443:443
        image: 'uozi/nginx-ui:latest'