services:
  minio:
    image: minio/minio
    container_name: de_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}  # Логин (замените на свой)
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}  # Пароль (обязательно замените!)
    volumes:
      - ./minio_data:/data  # Локальная папка для хранения данных
    # ports:
    #   - "9010:9000"  # S3 API
    #   - "9001:9001"  # Web Console
    networks:
      - minio

networks:
  minio:
    external: true
    name: de_frontend