services:
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "labyntsev"  # Логин (замените на свой)
      MINIO_ROOT_PASSWORD: "minio"  # Пароль (обязательно замените!)
    volumes:
      - ./minio_data:/data  # Локальная папка для хранения данных
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web Console
    networks:
      - minio_network

networks:
  minio_network:
    driver: bridge