services:
  minio:
    image: minio/minio
    container_name: de_minio
    restart: unless-stopped
    command: server /data --address ':9000' --console-address ':9001'
    environment:
      MINIO_SERVER_URL: "http://minio.de-project.space/"
      MINIO_BROWSER_REDIRECT_URL: "http://minio.de-project.space/console/"
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}  # Логин (замените на свой)
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}  # Пароль (обязательно замените!)
    volumes:
      - ./minio_data:/data  # Локальная папка для хранения данных
    # ports:
    #   - "9010:9000"  # S3 API
    #   - "9001:9001"  # Web Console
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio

networks:
  minio:
    external: true
    name: de_frontend