services:
    nginx-ui:
        stdin_open: true
        tty: true
        container_name: nginx-ui
        restart: always
        environment:
            - TZ=Russia/Moscow
        volumes:
            - ./nginx:/etc/nginx
            - ./nginx-ui:/etc/nginx-ui
            - ./www:/var/www
           # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/certs:/etc/nginx/certs
            - ./nginx/logs:/var/log/nginx
        ports:
            - 8080:80
            - 8443:443
        image: 'uozi/nginx-ui:latest'