name: Deploy_DE_Market

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 194.87.144.39
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        script: |
          cd /home/DE_Market
          git pull origin main
          sudo systemctl start docker.service
          echo -e "AIRFLOW_UID=$(id -u)" > .env
          cd /home/DE_Market/airflow
          sudo docker-compose up -d
